import type { ArtifactRule } from 'extension'
import { deepClone } from '~/composables/useUtils'

const defaultArtifactRule = {
  skill: {
    1001: 50,
    2001: 50,
    3001: 50,
    3002: 50,
    3003: 50,
    3004: 50,
    3005: 50,
    3006: 50,
    3007: 50,
    3008: 50,
    3009: 50,
    3010: 50,
    3011: 50,
    3012: 50,
    3013: 50,
    3014: 50,
    3015: 50,
    3016: 50,
    3017: 50,
    3018: 50,
    3019: 50,
    3020: 50,
    3021: 50,
    3022: 50,
    3023: 50,
    3024: 50,
    3025: 50,
    3026: 50,
    3027: 50,
    3028: 50,
    3029: 50,
    3030: 50,
    3031: 50,
    3032: 50,
    4001: 50,
    5001: 50,
    5002: 50,
    5003: 50,
    5004: 50,
    5005: 50,
    5006: 50,
    5007: 50,
    5008: 50,
    5010: 50,
    5011: 50,
    5012: 50,
    5013: 50,
    5014: 50,
    5015: 50,
    5016: 50,
    5017: 50,
    5018: 50,
    5019: 50,
    5020: 50,
    5021: 50,
    5022: 50,
    5023: 50,
    5024: 50,
    5025: 50,
    5026: 50,
    5027: 50,
    5028: 50,
    5029: 50,
  },
  kind: { '01': 100, '02': 100, '03': 100, '04': 100, '05': 100, '06': 100, '07': 100, '08': 100, '09': 100, '10': 100 },
  attribute: { 1: 100, 2: 100, 3: 100, 4: 100, 5: 100, 6: 100 },
  extra: {},
  highlight: {},
}

export const defaultArtifactRuleList: ArtifactRule[] = Array.from({ length: 6 }, (_, i) => ({
  name: `Rule ${i + 1}`,
  info: deepClone(defaultArtifactRule),
}))

export const artifactSkillList = {
  skill1: [
    {
      skillId: 1001,
      name: '攻撃力',
      nameEn: 'ATK',
      filterId: 1,
    },
    {
      skillId: 2001,
      name: 'HP',
      nameEn: 'HP',
      filterId: 2,
    },
    {
      skillId: 3001,
      name: 'クリティカル確率',
      nameEn: 'Critical Hit Rate',
      filterId: 3,
    },
    {
      skillId: 3002,
      name: '奥義ダメージ',
      nameEn: 'C.A. DMG',
      filterId: 4,
    },
    {
      skillId: 3003,
      name: 'アビリティダメージ',
      nameEn: 'Skill DMG',
      filterId: 5,
    },
    {
      skillId: 3004,
      name: 'Debuff Success Rate',
      nameEn: 'Debuff Success Rate',
      filterId: 6,
    },
    {
      skillId: 3005,
      name: 'ダブルアタック確率',
      nameEn: 'DA',
      filterId: 7,
    },
    {
      skillId: 3006,
      name: 'トリプルアタック確率',
      nameEn: 'TA',
      filterId: 8,
    },
    {
      skillId: 3007,
      name: 'DEF',
      nameEn: 'DEF',
      filterId: 9,
    },
    {
      skillId: 3008,
      name: '弱体耐性',
      nameEn: 'Debuff Resistance',
      filterId: 10,
    },
    {
      skillId: 3009,
      name: '回避率',
      nameEn: 'Dodge Rate',
      filterId: 11,
    },
    {
      skillId: 3010,
      name: '回復性能',
      nameEn: 'Healing',
      filterId: 12,
    },
    {
      skillId: 3011,
      name: '自属性攻撃力',
      nameEn: 'Elemental ATK',
      filterId: 13,
    },
    {
      skillId: 3012,
      name: '有利Element軽減',
      nameEn: 'Superior Element Reduction',
      filterId: 14,
    },
  ],
  skill2: [
    {
      skillId: 3013,
      name: '通常攻撃ダメージCap',
      nameEn: 'N.A DMG Cap',
      filterId: 15,
    },
    {
      skillId: 3014,
      name: 'アビリティダメージCap',
      nameEn: 'Skill DMG Cap',
      filterId: 16,
    },
    {
      skillId: 3015,
      name: '奥義ダメージCap',
      nameEn: 'C.A. DMG Cap',
      filterId: 17,
    },
    {
      skillId: 3016,
      name: '通常攻撃の与ダメージ上昇',
      nameEn: 'Supplemental N.A. DMG',
      filterId: 18,
    },
    {
      skillId: 3017,
      name: 'アビリティ与ダメージ上昇',
      nameEn: 'Supplemental Skill DMG',
      filterId: 19,
    },
    {
      skillId: 3018,
      name: '奥義与ダメージ上昇',
      nameEn: 'Supplemental C.A. DMG',
      filterId: 20,
    },
    {
      skillId: 3019,
      name: '奥義ダメージ特殊CapUP',
      nameEn: 'Special C.A. DMG Cap',
      filterId: 21,
    },
    {
      skillId: 3020,
      name: 'チェイン与ダメージUP',
      nameEn: 'Chain DMG Amplify',
      filterId: 22,
    },
    {
      skillId: 3021,
      name: 'ターンダメージを軽減',
      nameEn: 'Turn-Based DMG Reduction',
      filterId: 23,
    },
    {
      skillId: 3022,
      name: 'Regeneration',
      nameEn: 'Regeneration',
      filterId: 24,
    },
    {
      skillId: 3023,
      name: 'HPが100%の時、与ダメージUP',
      nameEn: 'Amplify DMG at 100% HP',
      filterId: 25,
    },
    {
      skillId: 3024,
      name: 'HPが50%以上の時、トリプルアタック確率UP',
      nameEn: 'Boost triple attack rate when at or above 50% HP',
      filterId: 26,
    },
    {
      skillId: 3025,
      name: 'HPが50%以下の時、被ダメージを軽減',
      nameEn: 'DMG reduction when at or below 50% HP',
      filterId: 27,
    },
    {
      skillId: 3026,
      name: 'クリティカル発動時、ダメージ上限UP',
      nameEn: 'Boost DMG cap for critical hits',
      filterId: 28,
    },
    {
      skillId: 3027,
      name: '最大HP上昇/DEF力-70%',
      nameEn: 'Max HP boost for a 70% hit to DEF',
      filterId: 29,
    },
    {
      skillId: 3028,
      name: '通常攻撃ダメージ上限UP/アビリティダメージCap-80%/奥義ダメージCap-60%',
      nameEn: 'N.A DMG Cap UP/Skill DMG Cap-80%/C.A. DMG Cap-60%',
      filterId: 30,
    },
    {
      skillId: 3029,
      name: 'アビリティダメージ上限UP/通常攻撃ダメージCap-20%/奥義ダメージCap-60%',
      nameEn: 'Skill DMG Cap UP/N.A DMG Cap-20%/C.A. DMG Cap-60%',
      filterId: 31,
    },
    {
      skillId: 3030,
      name: '奥義ダメージ上限UP/通常攻撃ダメージCap-20%/アビリティダメージCap-80%',
      nameEn: 'C.A. DMG Cap UP/N.A DMG Cap-20%/Skill DMG Cap-80%',
      filterId: 32,
    },
    {
      skillId: 4001,
      name: '確率で強化効果が無効化されない',
      nameEn: 'Chance to avoid incoming dispels',
      filterId: 33,
    },
    {
      skillId: 5001,
      name: '確率で攻撃開始時に自分の弱体効果を1つ回復',
      nameEn: 'Chance to remove 1 debuff before attacking',
      filterId: 34,
    },
  ],
  skill3: [
    {
      skillId: 5002,
      name: '弱体アビリティ使用時、敵に被ダメージUP(2回)',
      nameEn: 'Upon using a debuff skill: Amplify foe\'s DMG taken (2回)',
      filterId: 35,
    },
    {
      skillId: 5003,
      name: '回復アビリティ使用時、自分の次に配置されたキャラに自属性追撃効果(1回)',
      nameEn: 'Upon using healing skill: Ally in the next position gains Bonus DMG (1 time) with a value of x',
      filterId: 36,
    },
    {
      skillId: 5004,
      name: 'リンクアビリティを一定回数使用時に自分のリンクアビリティの再使用間隔を1ターン短縮',
      nameEn: 'Cut linked skill cooldowns by 1 turn after using a linked skill x times',
      filterId: 37,
    },
    {
      skillId: 5005,
      name: '使用間隔が10ターン以上のアビリティ使用時、自分に与ダメージUP',
      nameEn: 'Upon After using a skill with a cooldown of 10 or more turns: Gain x% All DMG Amplified',
      filterId: 38,
    },
    {
      skillId: 5006,
      name: 'アビリティを一定回数使用する度に自分にダメージ上限UP(累積)',
      nameEn: 'Gain 1% DMG Cap Up (Stackable / Max: 5%) after using skills x time(s)',
      filterId: 39,
    },
    {
      skillId: 5007,
      name: 'アビリティダメージを一定量与える毎に自分にアビリティ与ダメージ上昇(累積)',
      nameEn: 'Gain Supplemental Skill DMG (Stackable / Max: 50,000)after dealing this amount of skill DMG x times',
      filterId: 40,
    },
    {
      skillId: 5008,
      name: '1回攻撃発動時、自分に一定個数ランダムな強化効果',
      nameEn: 'Upon single attacks: Gain x random buff(s)',
      filterId: 41,
    },
    {
      skillId: 5010,
      name: 'ターン終了時、自分がそのターン中に消費したHPに応じて敵に無Elementダメージ',
      nameEn: 'Plain DMG to a foe at end of turn based on how much HP the equipper lost that turn',
      filterId: 42,
    },
    {
      skillId: 5011,
      name: 'ターン終了時、自分がそのターン中に消費した奥義ゲージ量に応じて自分に与ダメージ上昇',
      nameEn: 'Gain Supplemental DMG at end of turn based on amount of charge bar spent that turn',
      filterId: 43,
    },
    {
      skillId: 5012,
      name: '攻撃開始時に敵の弱体効果の数が3つ以下の時、自分にブロック効果',
      nameEn: 'When a foe has 3 or fewer debuffs at turn start: Equipper gains Armored with a strength of x ',
      filterId: 44,
    },
    {
      skillId: 5013,
      name: 'ターン終了時にHPが50%以下の敵がいる時、一度だけ自分のHPを回復',
      nameEn: 'At Turn End, If Any Enemy HP <50%, Recover HP (Once) | When a foe\'s HP is at 50% or lower at end of turn (1 time): Restore equipper\'s HP by x ',
      filterId: 45,
    },
    {
      skillId: 5014,
      name: 'サブメンバー時、一定ターン毎に敵全体にランダムな弱体効果を1つ付与(重複不可)',
      nameEn: 'When a sub ally (Max 1 of this skill per party): 1 random debuff to all foes every x turns',
      filterId: 46,
    },
    {
      skillId: 5015,
      name: '一定回数敵の攻撃行動のターゲットになった場合、一度だけ自分に自属性追撃(1回)効果',
      nameEn: 'Gain 20% Bonus DMG (1 time) after being targeted by foes\' attacks x time(s)',
      filterId: 47,
    },
    {
      skillId: 5016,
      name: '攻撃行動を行わなかった場合、ターン終了時に自分に一定個数ランダムな強化効果',
      nameEn: 'At end of turn if equipper didn\'t attack: Gain x random buff(s)',
      filterId: 48,
    },
    {
      skillId: 5017,
      name: 'キュアポーションまたはオールポーション使用時にフェイタルチェインゲージUP(重複不可)',
      nameEn: 'Upon using a green or blue potion (Max 1 of this skill per party): Boost Fated Chain bar by x ',
      filterId: 49,
    },
    {
      skillId: 5018,
      name: '敵に一定回数攻撃を与えた時、一度だけ自分に乱撃(3ヒット)効果(1回)',
      nameEn: 'Gain Flurry (3-hit / 1 time) after hitting a foe x times',
      filterId: 50,
    },
    {
      skillId: 5019,
      name: '戦闘不能になった時、一度だけ味方全体に一定個数ランダムな強化効果',
      nameEn: ' When knocked out (1 time): All allies gain x random buff(s)',
      filterId: 51,
    },
    {
      skillId: 5020,
      name: 'バトル登場時に一度だけ自分の与ダメージUP',
      nameEn: 'When switching to a main ally (1 time): Gain x% All DMG Amplified',
      filterId: 52,
    },
    {
      skillId: 5021,
      name: 'バトル開始時に自分に一定個数ランダムな強化効果',
      nameEn: 'At battle start: Gain x random buff(s)',
      filterId: 53,
    },
    {
      skillId: 5022,
      name: 'バトル開始時から1ターンの間被ダメージ減少',
      nameEn: 'At battle start: Gain DMG Mitigation with a value of x ',
      filterId: 54,
    },
    {
      skillId: 5023,
      name: 'バトル開始時と5ターン毎に自分にバリア効果',
      nameEn: 'At battle start and every 5 turns: Gain Shield with a value of x',
      filterId: 55,
    },
    {
      skillId: 5024,
      name: 'バトル開始時に最大HPの20%を消費するが3ターン後、自分にダメージ上限UP',
      nameEn: 'Start battle with 20% of HP consumed and Readying Skill (DMG Cap Up) / After 3 turns: Gain x% DMG Cap Up',
      filterId: 56,
    },
    {
      skillId: 5025,
      name: '1番目のアビリティ使用時にHPを一定割合消費するが、1番目のアビリティの使用間隔を1ターン短縮(レベルに応じて消費割合DOWN)',
      nameEn: 'Skill 1 Consumes HP and Reduces Cooldown by 1 Turn (Higher Level = Less HP Cost) | Upon casting first-slot skill: Cut first-slot skill\'s cooldown by 1 turn and consume this percentage of current HP (HP consumption lowers with higher lvls of this artifact skill)',
      filterId: 57,
    },
    {
      skillId: 5026,
      name: '攻撃開始時、確率で自分に乱撃(6ヒット)効果(1回)',
      nameEn: 'At turn start, chance to gain Flurry (6-hit / 1 time)',
      filterId: 58,
    },
    {
      skillId: 5027,
      name: '確率でターンの進行時に経過ターンを5ターン進める(重複不可)',
      nameEn: 'Chance of battle turn progressing by 5 at end of turn (Max 1 of this skill per party)',
      filterId: 59,
    },
    {
      skillId: 5028,
      name: 'ターン終了時、確率で敵の強化効果を全て無効化(重複不可)',
      nameEn: 'Chance to remove all buffs from a foe at end of turn',
      filterId: 60,
    },
    {
      skillId: 3031,
      name: 'アイテムドロップ率UP(重複不可) ◆サブメンバーにいる場合でも発動',
      nameEn: 'Boost item drop rate by x% (◆Even when sub ally/ max 1 of this skill per party)',
      filterId: 61,
    },
    {
      skillId: 3032,
      name: '獲得経験値UP(重複不可) ◆サブメンバーにいる場合でも発動',
      nameEn: 'Boost EXP earned by x% (◆Even when sub ally/ max 1 of this skill per party)',
      filterId: 62,
    },
    {
      skillId: 5029,
      name: 'バトル終了時にランダムな耳飾りを入手することがある(レベルに応じて入手確率UP/重複不可) ◆サブメンバーにいる場合でも発動',
      nameEn: 'May find a random pair of earrings at end of battle  (◆Even when sub ally/ max 1 of this skill per party/ Chance increases with higher lvl)',
      filterId: 63,
    },
  ],
}
