import type { ArtifactRule } from 'extension'

const defaultArtifactRule = {
  skill: {
    1001: 50,
    2001: 50,
    3001: 50,
    3002: 50,
    3003: 50,
    3004: 50,
    3005: 50,
    3006: 50,
    3007: 50,
    3008: 50,
    3009: 50,
    3010: 50,
    3011: 50,
    3012: 50,
    3013: 50,
    3014: 50,
    3015: 50,
    3016: 50,
    3017: 50,
    3018: 50,
    3019: 50,
    3020: 50,
    3021: 50,
    3022: 50,
    3023: 50,
    3024: 50,
    3025: 50,
    3026: 50,
    3027: 50,
    3028: 50,
    3029: 50,
    3030: 50,
    3031: 50,
    3032: 50,
    4001: 50,
    5001: 50,
    5002: 50,
    5003: 50,
    5004: 50,
    5005: 50,
    5006: 50,
    5007: 50,
    5008: 50,
    5010: 50,
    5011: 50,
    5012: 50,
    5013: 50,
    5014: 50,
    5015: 50,
    5016: 50,
    5017: 50,
    5018: 50,
    5019: 50,
    5020: 50,
    5021: 50,
    5022: 50,
    5023: 50,
    5024: 50,
    5025: 50,
    5026: 50,
    5027: 50,
    5028: 50,
    5029: 50,
  },
  kind: { '01': 100, '02': 100, '03': 100, '04': 100, '05': 100, '06': 100, '07': 100, '08': 100, '09': 100, '10': 100 },
  attribute: { 1: 100, 2: 100, 3: 100, 4: 100, 5: 100, 6: 100 },
  extra: {},
  highlight: {},
}

export const defaultArtifactRuleList: ArtifactRule[] = Array.from({ length: 6 }, (_, i) => ({
  name: `规则${i + 1}`,
  info: deepClone(defaultArtifactRule),
}))

export const artifactSkillList = {
  skill1: [
    {
      skillId: 1001,
      name: '攻撃力',
      nameZh: '攻击力',
      filterId: 1,
    },
    {
      skillId: 2001,
      name: 'HP',
      nameZh: '血量',
      filterId: 2,
    },
    {
      skillId: 3001,
      name: 'クリティカル確率',
      nameZh: '暴击率',
      filterId: 3,
    },
    {
      skillId: 3002,
      name: '奥義ダメージ',
      nameZh: '奥义伤害',
      filterId: 4,
    },
    {
      skillId: 3003,
      name: 'アビリティダメージ',
      nameZh: '技能伤害',
      filterId: 5,
    },
    {
      skillId: 3004,
      name: '弱体成功率',
      nameZh: '弱体成功率',
      filterId: 6,
    },
    {
      skillId: 3005,
      name: 'ダブルアタック確率',
      nameZh: 'DA',
      filterId: 7,
    },
    {
      skillId: 3006,
      name: 'トリプルアタック確率',
      nameZh: 'TA',
      filterId: 8,
    },
    {
      skillId: 3007,
      name: '防御',
      nameZh: '防御',
      filterId: 9,
    },
    {
      skillId: 3008,
      name: '弱体耐性',
      nameZh: '弱体耐性',
      filterId: 10,
    },
    {
      skillId: 3009,
      name: '回避率',
      nameZh: '回避率',
      filterId: 11,
    },
    {
      skillId: 3010,
      name: '回復性能',
      nameZh: '回复性能',
      filterId: 12,
    },
    {
      skillId: 3011,
      name: '自属性攻撃力',
      nameZh: '自属性攻击力',
      filterId: 13,
    },
    {
      skillId: 3012,
      name: '有利属性軽減',
      nameZh: '有利属性伤害减轻',
      filterId: 14,
    },
  ],
  skill2: [
    {
      skillId: 3013,
      name: '通常攻撃ダメージ上限',
      nameZh: '普攻伤害上限',
      filterId: 15,
    },
    {
      skillId: 3014,
      name: 'アビリティダメージ上限',
      nameZh: '技能伤害上限',
      filterId: 16,
    },
    {
      skillId: 3015,
      name: '奥義ダメージ上限',
      nameZh: '奥义伤害上限',
      filterId: 17,
    },
    {
      skillId: 3016,
      name: '通常攻撃の与ダメージ上昇',
      nameZh: '普攻与伤上升',
      filterId: 18,
    },
    {
      skillId: 3017,
      name: 'アビリティ与ダメージ上昇',
      nameZh: '技能与伤上升',
      filterId: 19,
    },
    {
      skillId: 3018,
      name: '奥義与ダメージ上昇',
      nameZh: '奥义与伤上升',
      filterId: 20,
    },
    {
      skillId: 3019,
      name: '奥義ダメージ特殊上限UP',
      nameZh: '奥义特殊上限UP',
      filterId: 21,
    },
    {
      skillId: 3020,
      name: 'チェイン与ダメージUP',
      nameZh: '连锁与伤上升',
      filterId: 22,
    },
    {
      skillId: 3021,
      name: 'ターンダメージを軽減',
      nameZh: '回合伤害减轻',
      filterId: 23,
    },
    {
      skillId: 3022,
      name: '再生',
      nameZh: '再生',
      filterId: 24,
    },
    {
      skillId: 3023,
      name: 'HPが100%の時、与ダメージUP',
      nameZh: '满血时与伤上升',
      filterId: 25,
    },
    {
      skillId: 3024,
      name: 'HPが50%以上の時、トリプルアタック確率UP',
      nameZh: '血量50%以上时TA几率UP',
      filterId: 26,
    },
    {
      skillId: 3025,
      name: 'HPが50%以下の時、被ダメージを軽減',
      nameZh: '血量50%以下时受伤减轻',
      filterId: 27,
    },
    {
      skillId: 3026,
      name: 'クリティカル発動時、ダメージ上限UP',
      nameZh: '暴击时伤害上限UP',
      filterId: 28,
    },
    {
      skillId: 3027,
      name: '最大HP上昇/防御力-70%',
      nameZh: '最大血量上升/防御力-70%',
      filterId: 29,
    },
    {
      skillId: 3028,
      name: '通常攻撃ダメージ上限UP/アビリティダメージ上限-80%/奥義ダメージ上限-60%',
      nameZh: '普攻上限UP/技能上限-80%/奥义上限-60%',
      filterId: 30,
    },
    {
      skillId: 3029,
      name: 'アビリティダメージ上限UP/通常攻撃ダメージ上限-20%/奥義ダメージ上限-60%',
      nameZh: '技能上限UP/普攻上限-20%/奥义上限-60%',
      filterId: 31,
    },
    {
      skillId: 3030,
      name: '奥義ダメージ上限UP/通常攻撃ダメージ上限-20%/アビリティダメージ上限-80%',
      nameZh: '奥义上限UP/普攻上限-20%/技能上限-80%',
      filterId: 32,
    },
    {
      skillId: 4001,
      name: '確率で強化効果が無効化されない',
      nameZh: '一定几率免疫驱散',
      filterId: 33,
    },
    {
      skillId: 5001,
      name: '確率で攻撃開始時に自分の弱体効果を1つ回復',
      nameZh: '一定几率攻击时净化自身一个弱体效果',
      filterId: 34,
    },
  ],
  skill3: [
    {
      skillId: 5002,
      name: '弱体アビリティ使用時、敵に被ダメージUP(2回)',
      nameZh: '使用弱体技能时赋予敌方受伤UP(2次)',
      filterId: 35,
    },
    {
      skillId: 5003,
      name: '回復アビリティ使用時、自分の次に配置されたキャラに自属性追撃効果(1回)',
      nameZh: '使用回复技能时赋予下一个角色自属性追伤(1次)',
      filterId: 36,
    },
    {
      skillId: 5004,
      name: 'リンクアビリティを一定回数使用時に自分のリンクアビリティの再使用間隔を1ターン短縮',
      nameZh: '每使用一定次数的连接技能缩短自身连接技能再使用间隔1回合',
      filterId: 37,
    },
    {
      skillId: 5005,
      name: '使用間隔が10ターン以上のアビリティ使用時、自分に与ダメージUP',
      nameZh: '使用使用间隔10回合以上的技能后自身获得与伤UP',
      filterId: 38,
    },
    {
      skillId: 5006,
      name: 'アビリティを一定回数使用する度に自分にダメージ上限UP(累積)',
      nameZh: '使用一定次数的技能后自身伤害上限UP(累积)',
      filterId: 39,
    },
    {
      skillId: 5007,
      name: 'アビリティダメージを一定量与える毎に自分にアビリティ与ダメージ上昇(累積)',
      nameZh: '造成一定量技能伤害后自身技能与伤上升(累积)',
      filterId: 40,
    },
    {
      skillId: 5008,
      name: '1回攻撃発動時、自分に一定個数ランダムな強化効果',
      nameZh: 'SA时自身获得一定个数随机强化效果',
      filterId: 41,
    },
    {
      skillId: 5010,
      name: 'ターン終了時、自分がそのターン中に消費したHPに応じて敵に無属性ダメージ',
      nameZh: '根据本回合消耗的HP在回合结束时对敌方造成无属性伤害',
      filterId: 42,
    },
    {
      skillId: 5011,
      name: 'ターン終了時、自分がそのターン中に消費した奥義ゲージ量に応じて自分に与ダメージ上昇',
      nameZh: '根据本回合消耗的奥义值在回合结束时自身与伤上升',
      filterId: 43,
    },
    {
      skillId: 5012,
      name: '攻撃開始時に敵の弱体効果の数が3つ以下の時、自分にブロック効果',
      nameZh: '攻击开始时若敌方弱体少于3个, 自身获得格挡效果',
      filterId: 44,
    },
    {
      skillId: 5013,
      name: 'ターン終了時にHPが50%以下の敵がいる時、一度だけ自分のHPを回復',
      nameZh: '回合结束时若敌方血量低于50%, 自身HP回复(只触发一次)',
      filterId: 45,
    },
    {
      skillId: 5014,
      name: 'サブメンバー時、一定ターン毎に敵全体にランダムな弱体効果を1つ付与(重複不可)',
      nameZh: '后排时每经过一定回合就对敌方全体释放一个随机弱体效果(不能叠加)',
      filterId: 46,
    },
    {
      skillId: 5015,
      name: '一定回数敵の攻撃行動のターゲットになった場合、一度だけ自分に自属性追撃(1回)効果',
      nameZh: '成为一定次数的攻击目标后自身获得自属性追伤(1次/只触发一次)',
      filterId: 47,
    },
    {
      skillId: 5016,
      name: '攻撃行動を行わなかった場合、ターン終了時に自分に一定個数ランダムな強化効果',
      nameZh: '没有进行攻击的回合结束时自身获得一定个数随机强化效果',
      filterId: 48,
    },
    {
      skillId: 5017,
      name: 'キュアポーションまたはオールポーション使用時にフェイタルチェインゲージUP(重複不可)',
      nameZh: '使用绿药和蓝药时FC槽充能UP(不能叠加)',
      filterId: 49,
    },
    {
      skillId: 5018,
      name: '敵に一定回数攻撃を与えた時、一度だけ自分に乱撃(3ヒット)効果(1回)',
      nameZh: '对敌方造成一定次数攻击后自身获得乱击效果(3hit/1次/只触发一次)',
      filterId: 50,
    },
    {
      skillId: 5019,
      name: '戦闘不能になった時、一度だけ味方全体に一定個数ランダムな強化効果',
      nameZh: '角色死亡时己方全体获得一定个数的随机强化效果(只触发一次)',
      filterId: 51,
    },
    {
      skillId: 5020,
      name: 'バトル登場時に一度だけ自分の与ダメージUP',
      nameZh: '登场时自身与伤UP(只触发一次)',
      filterId: 52,
    },
    {
      skillId: 5021,
      name: 'バトル開始時に自分に一定個数ランダムな強化効果',
      nameZh: '战斗开始时赋予自身一定个数随机强化效果',
      filterId: 53,
    },
    {
      skillId: 5022,
      name: 'バトル開始時から1ターンの間被ダメージ減少',
      nameZh: '战斗开始时赋予自身一回合受伤减免',
      filterId: 54,
    },
    {
      skillId: 5023,
      name: 'バトル開始時と5ターン毎に自分にバリア効果',
      nameZh: '战斗开始以及每五回合赋予自身护盾效果',
      filterId: 55,
    },
    {
      skillId: 5024,
      name: 'バトル開始時に最大HPの20%を消費するが3ターン後、自分にダメージ上限UP',
      nameZh: '战斗开始时消耗最大HP的20%, 3回合后自身伤害上限UP',
      filterId: 56,
    },
    {
      skillId: 5025,
      name: '1番目のアビリティ使用時にHPを一定割合消費するが、1番目のアビリティの使用間隔を1ターン短縮(レベルに応じて消費割合DOWN)',
      nameZh: '1技能使用时消耗一定比例HP, 使用间隔减少1回合(等级越高消耗HP越少)',
      filterId: 57,
    },
    {
      skillId: 5026,
      name: '攻撃開始時、確率で自分に乱撃(6ヒット)効果(1回)',
      nameZh: '攻击开始时一定几率自身乱击效果(6hit/1次)',
      filterId: 58,
    },
    {
      skillId: 5027,
      name: '確率でターンの進行時に経過ターンを5ターン進める(重複不可)',
      nameZh: '一定几率回合结束时前进5回合(不能叠加)',
      filterId: 59,
    },
    {
      skillId: 5028,
      name: 'ターン終了時、確率で敵の強化効果を全て無効化(重複不可)',
      nameZh: '一定几率回合结束时驱散敌方所有强化效果(不能叠加)',
      filterId: 60,
    },
    {
      skillId: 3031,
      name: 'アイテムドロップ率UP(重複不可) ◆サブメンバーにいる場合でも発動',
      nameZh: '物品掉率UP(不能叠加) ◆前后排均有效',
      filterId: 61,
    },
    {
      skillId: 3032,
      name: '獲得経験値UP(重複不可) ◆サブメンバーにいる場合でも発動',
      nameZh: '经验值UP(不能叠加) ◆前后排均有效',
      filterId: 62,
    },
    {
      skillId: 5029,
      name: 'バトル終了時にランダムな耳飾りを入手することがある(レベルに応じて入手確率UP/重複不可) ◆サブメンバーにいる場合でも発動',
      nameZh: '回合结束时一定几率随机获得耳环(等级越高几率越高/不能叠加) ◆前后排均有效',
      filterId: 63,
    },
  ],
}
