export const weaponSkill = [
  {
    series_id: ['3'],
    name: 'Opus Weapon Key',
    type: 'skill3',
    list: [{
      id: '4048',
      name: '強壮のペンデュラム',
      alias: '浑身',
      comment: 'キャラのHPが多いほど攻撃力が上昇(大)',
      comment_en: 'allies\' ATK based on how high HP is',
    }, {
      id: '4049',
      name: '激情のペンデュラム',
      alias: '背水',
      comment: 'キャラのHPが少ないほど攻撃力が上昇(大)',
      comment_en: 'allies\' ATK based on how low HP is',
    }, {
      id: '4050',
      name: '闘争のペンデュラム',
      alias: 'DATA',
      comment: 'キャラの連続攻撃確率上昇(中)',
      comment_en: 'allies\' multiattack rate',
    }, {
      id: '4051',
      name: '隆盛のペンデュラム',
      alias: '进境',
      comment: 'Element攻撃力が上昇(大)',
      comment_en: 'ATK based on number of turns passed',
    }, {
      id: '6153',
      name: '技錬のチェイン',
      alias: 'Critical',
      comment: 'キャラの攻撃力上昇(中)/クリティカル確率上昇(中)',
      comment_en: 'allies\' ATK and critical hit rate',
    }, {
      id: '6154',
      name: '賦活のチェイン',
      alias: 'Majesty',
      comment: 'キャラの攻撃力と最大HPが上昇(中)',
      comment_en: 'allies\' ATK and max HP',
    }, {
      id: '6155',
      name: '謳歌のチェイン',
      alias: 'Glorification (C.A.)',
      comment: 'キャラの奥義性能UP(大)/チェインバースト性能UP(大)',
      comment_en: 'allies\' C.A. specs and chain burst specs',
    }, {
      id: '6156',
      name: '誘惑のチェイン',
      alias: 'Temptation (Freyr)',
      comment: 'バトル開始時に様々な強化効果/最大HP-30%',
      comment_en: 'At start of battle: Various buffs to all allies / 30% hit to max HP',
    }, {
      id: '6157',
      name: 'Forbiddance (Apple)のチェイン',
      alias: 'Forbiddance (Apple)',
      comment: '奥義性能UP/奥義発動時にダメージを受ける',
      comment_en: 'Boost to C.A. specs / Take DMG upon using charge attack',
    }, {
      id: '6158',
      name: 'Depravity (Plain DMG)のチェイン',
      alias: 'Depravity (Plain DMG)',
      comment: '自分のHPが50%以下の時、ターン終了時敵全体に無Elementダメージ/毎ターンダメージを受ける',
      comment_en: 'Plain DMG to all foes at end of turn when HP is 50% or below / Take DMG every turn',
    }, {
      id: '6159',
      name: '虚詐のチェイン',
      alias: 'Falsehood (Eresh)',
      comment: '自属性追撃効果/奥義ゲージ上昇量大幅DOWN',
      comment_en: 'Bonus Elemental DMG effect / Sharp hit to charge bar gain',
    }, {
      id: '14005',
      name: '絶涯のペンデュラム',
      alias: 'Extremity (N.A.)',
      comment: '通常攻撃の与ダメージUP',
      comment_en: 'Amplify normal attack DMG',
    }, {
      id: '14006',
      name: '窮理のペンデュラム',
      alias: 'Sagacity (Skill)',
      comment: 'アビリティの与ダメージUP',
      comment_en: 'Amplify skill DMG',
    }, {
      id: '14007',
      name: '天髄のペンデュラム',
      alias: 'Supremacy (C.A.)',
      comment: '奥義の与ダメージUP',
      comment_en: 'Amplify chain burst DMG',
    }],
  },
  {
    series_id: ['13'],
    name: 'Ultima Weapon Key',
    type: 'skill3',
    list: [{
      id: '6549',
      name: 'ガフスキー【エナ】',
      alias: 'Cap',
      comment: 'ダメージCap上昇',
      comment_en: 'Boost to all allies\' DMG cap',
    }, {
      id: '6550',
      name: 'ガフスキー【ディオ】',
      alias: 'Recovery',
      comment: '回復Cap上昇',
      comment_en: 'Boost to all allies\' healing cap',
    }, {
      id: '6551',
      name: 'ガフスキー【トリア】',
      alias: 'Seraphic',
      comment: '有利なElementの敵に対して与ダメージUP',
      comment_en: 'Amplify all allies\' superior elemental DMG',
    }, {
      id: '6552',
      name: 'ガフスキー【テーセラ】',
      alias: 'C.A.',
      comment: '奥義ゲージ上昇量UP',
      comment_en: 'Boost to all allies\' charge bar gain',
    }],
  },
  {
    series_id: ['27', '40'],
    name: 'Draconic Weapon Teluma',
    type: 'skill2',
    list: [{
      id: '4995',
      name: '剛堅のテルマ',
      alias: 'DEF',
      comment: 'DEF力上昇',
      comment_en: 'Boost to DEF',
    }, {
      id: '4996',
      name: '炎獄のテルマ',
      alias: 'Fire Damage Reduction',
      comment: '火Elementダメージ軽減',
      comment_en: 'Fire DMG reduction',
    }, {
      id: '4997',
      name: '深海のテルマ',
      alias: 'Water Damage Reduction',
      comment: '水Elementダメージ軽減',
      comment_en: 'Water DMG reduction',
    }, {
      id: '4998',
      name: '巨岩のテルマ',
      alias: 'Earth Damage Reduction',
      comment: '土Elementダメージ軽減',
      comment_en: 'Earth DMG reduction',
    }, {
      id: '4999',
      name: '暴風のテルマ',
      alias: 'Wind Damage Reduction',
      comment: '風Elementダメージ軽減',
      comment_en: 'Wind DMG reduction',
    }, {
      id: '5000',
      name: '後光のテルマ',
      alias: 'Light Damage Reduction',
      comment: '光Elementダメージ軽減',
      comment_en: 'Light DMG reduction',
    }, {
      id: '5001',
      name: '闇禍のテルマ',
      alias: 'Dark Damage Reduction',
      comment: '闇Elementダメージ軽減',
      comment_en: 'Dark DMG reduction',
    }, {
      id: '8606',
      name: '燦護のテルマ',
      alias: 'HP',
      comment: 'HPを10000上昇',
      comment_en: 'allies\' HP by 10,000',
    }, {
      id: '8607',
      name: '冥烈のテルマ',
      alias: 'Seraphic',
      comment: '無Elementの敵に対して与ダメージUP',
      comment_en: 'allies\' DMG against non-elemental foes',
    }],
  },
  {
    series_id: ['44'],
    name: 'Destruction Bangle',
    type: 'skill3',
    list: [
      {
        id: '100885',
        name: '崩焉のアンクレット',
        alias: 'Supplemental N.A. DMG',
        comment: '通常攻撃の与ダメージ上昇',
        comment_en: 'Supplement normal attack DMG',
      },
      {
        id: '100886',
        name: '越達のアンクレット',
        alias: 'Supplemental Skill DMG',
        comment: 'アビリティの与ダメージ上昇',
        comment_en: 'Supplement skill DMG',
      },
      {
        id: '100887',
        name: '竟極のアンクレット',
        alias: 'Supplemental C.A. DMG',
        comment: '奥義の与ダメージ上昇',
        comment_en: 'Supplement C.A. DMG',
      },
    ],
  },
]
