export const weaponSkill = [
  {
    series_id: '3',
    name: '法武插件',
    type: 'skill3',
    list: [{
      id: '4048',
      name: '強壮のペンデュラム',
      alias: '浑身',
      comment: 'キャラのHPが多いほど攻撃力が上昇(大)',
      comment_en: 'allies\' ATK based on how high HP is',
    }, {
      id: '4049',
      name: '激情のペンデュラム',
      alias: '背水',
      comment: 'キャラのHPが少ないほど攻撃力が上昇(大)',
      comment_en: 'allies\' ATK based on how low HP is',
    }, {
      id: '4050',
      name: '闘争のペンデュラム',
      alias: '连击',
      comment: 'キャラの連続攻撃確率上昇(中)',
      comment_en: 'allies\' multiattack rate',
    }, {
      id: '4051',
      name: '隆盛のペンデュラム',
      alias: '进境',
      comment: '属性攻撃力が上昇(大)',
      comment_en: 'ATK based on number of turns passed',
    }, {
      id: '6153',
      name: '技錬のチェイン',
      alias: '暴击',
      comment: 'キャラの攻撃力上昇(中)/クリティカル確率上昇(中)',
      comment_en: 'allies\' ATK and critical hit rate',
    }, {
      id: '6154',
      name: '賦活のチェイン',
      alias: '神威',
      comment: 'キャラの攻撃力と最大HPが上昇(中)',
      comment_en: 'allies\' ATK and max HP',
    }, {
      id: '6155',
      name: '謳歌のチェイン',
      alias: '讴歌',
      comment: 'キャラの奥義性能UP(大)/チェインバースト性能UP(大)',
      comment_en: 'allies\' C.A. specs and chain burst specs',
    }, {
      id: '6156',
      name: '誘惑のチェイン',
      alias: '诱惑',
      comment: 'バトル開始時に様々な強化効果/最大HP-30%',
      comment_en: 'At start of battle: Various buffs to all allies / 30% hit to max HP',
    }, {
      id: '6157',
      name: '禁忌のチェイン',
      alias: '禁忌',
      comment: '奥義性能UP/奥義発動時にダメージを受ける',
      comment_en: 'Boost to C.A. specs / Take DMG upon using charge attack',
    }, {
      id: '6158',
      name: '邪罪のチェイン',
      alias: '邪罪',
      comment: '自分のHPが50%以下の時、ターン終了時敵全体に無属性ダメージ/毎ターンダメージを受ける',
      comment_en: 'Plain DMG to all foes at end of turn when HP is 50% or below / Take DMG every turn',
    }, {
      id: '6159',
      name: '虚詐のチェイン',
      alias: '虚诈',
      comment: '自属性追撃効果/奥義ゲージ上昇量大幅DOWN',
      comment_en: 'Bonus Elemental DMG effect / Sharp hit to charge bar gain',
    }],
  },
  {
    series_id: '13',
    name: 'U武插件',
    type: 'skill3',
    list: [{
      id: '6549',
      name: 'ガフスキー【エナ】',
      alias: '上限',
      comment: 'ダメージ上限上昇',
      comment_en: 'Boost to all allies\' DMG cap',
    }, {
      id: '6550',
      name: 'ガフスキー【ディオ】',
      alias: '回复',
      comment: '回復上限上昇',
      comment_en: 'Boost to all allies\' healing cap',
    }, {
      id: '6551',
      name: 'ガフスキー【トリア】',
      alias: '天司',
      comment: '有利な属性の敵に対して与ダメージUP',
      comment_en: 'Amplify all allies\' superior elemental DMG',
    }, {
      id: '6552',
      name: 'ガフスキー【テーセラ】',
      alias: '奥义',
      comment: '奥義ゲージ上昇量UP',
      comment_en: 'Boost to all allies\' charge bar gain',
    }],
  },
  {
    series_id: ['27', '40'],
    name: '龙武插件',
    type: 'skill2',
    list: [{
      id: '4995',
      name: '剛堅のテルマ',
      alias: '防御',
      comment: '防御力上昇',
      comment_en: 'Boost to DEF',
    }, {
      id: '4996',
      name: '炎獄のテルマ',
      alias: '火减轻',
      comment: '火属性ダメージ軽減',
      comment_en: 'Fire DMG reduction',
    }, {
      id: '4997',
      name: '深海のテルマ',
      alias: '水减轻',
      comment: '水属性ダメージ軽減',
      comment_en: 'Water DMG reduction',
    }, {
      id: '4998',
      name: '巨岩のテルマ',
      alias: '土减轻',
      comment: '土属性ダメージ軽減',
      comment_en: 'Earth DMG reduction',
    }, {
      id: '4999',
      name: '暴風のテルマ',
      alias: '风减轻',
      comment: '風属性ダメージ軽減',
      comment_en: 'Wind DMG reduction',
    }, {
      id: '5000',
      name: '後光のテルマ',
      alias: '光减轻',
      comment: '光属性ダメージ軽減',
      comment_en: 'Light DMG reduction',
    }, {
      id: '5001',
      name: '闇禍のテルマ',
      alias: '暗减轻',
      comment: '闇属性ダメージ軽減',
      comment_en: 'Dark DMG reduction',
    }, {
      id: '8606',
      name: '燦護のテルマ',
      alias: '血量',
      comment: 'HPを10000上昇',
      comment_en: 'allies\' HP by 10,000',
    }, {
      id: '8607',
      name: '冥烈のテルマ',
      alias: '天司',
      comment: '無属性の敵に対して与ダメージUP',
      comment_en: 'allies\' DMG against non-elemental foes',
    }],
  },
]
