import '@unocss/reset/tailwind.css'
import './main.css'
import './detail.css'
import './room_member.css'
import 'uno.css'
import 'element-plus/theme-chalk/dark/css-vars.css'
import 'lxgw-wenkai-screen-webfont/style.css'
