import '@unocss/reset/tailwind.css'
import './main.css'
import './detail.css'
import './exlb.css'
import './room_member.css'
import 'uno.css'
import 'element-plus/dist/index.css'
import 'element-plus/theme-chalk/dark/css-vars.css'
