name: Release

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run bp
      - name: Zip
        run: pnpm run zip
      - name: Log
        env:
          OSS_ACCESSKEY_ID: ${{ secrets.OSS_ACCESSKEY_ID }}
          OSS_ACCESSKEY_SECRET: ${{ secrets.OSS_ACCESSKEY_SECRET }}
          OSS_BUCKET_FILE: ${{ secrets.OSS_BUCKET_FILE }}
        run: pnpm run log
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Chrome-Extension-Tarou v${{github.ref_name}}.zip
